### PR TITLE
parse refseq and fix c4r_db function

### PR DESCRIPTION
**Pull request by pamelaxu213**

### CODE REVIEW

**Comment by Madelinehazel** [comment]
Looking good @pamelaxu213. A few comments: 

- You don't need to [remove](https://github.com/Madelinehazel/slivar_reports/pull/9/files#diff-e6fc4826553a43c5ab2ae89cfa77829fbe65b3bb93dbb3560a976db83d459194L77) the highest_impact column and replace it with the 'Variation' column as populated by the Info field. Let's keep highest_impact, and take out 'Variation'. This does mean that the highest_impact value may not be the impact associated with the canonical RefSeq transcript, but that is OK. 
- Can you add the HGVS coding and protein annotations the the RefSeq_change column? The format would be [transcript_id]:[cDNA change]:[protein_change]. So, for example, variant 1:2290110:C:T should have the annotation NM_024848.3:c.790G>A:p.Val264Met
- can you write a few test in tests/test_parse_report.py for the parse_info() function? i.e. one for a case with a canonical RefSeq transcript, one for a case with no canonical RefSeq transcript, and one for a case with no RefSeq transcript at all (i.e. just an Ensembl transcript)?
- Also, when I run the tests, alt_depth(DP, AB) and test_replacedelim() fail- can you please modify these if the code they are testing has changed?

**Comment by Madelinehazel** [comment]
Almost there- I noticed one bug, which may be the result of the variant falling in canonical transcripts for two different genes. I think this is probably a rare case. For example, variant 1:35453771:T:G impacts a few genes, including the canonical transcripts for both ZMYM6 and TMEM35B. I think the issue here may require a few changes:

- Can you prefix the transcript with the gene name? e.g. MORN1:NM_024848.3:c.790G>A:p.Val264Met instead of NM_024848.3:c.790G>A:p.Val264Met. 
- If the variant falls in more than one canonical transcript, list both. E.g. TMEM35B:NM_001195156.1:NA,ZMYM6:NM_007167.4:c.2912A>C:p.Asn971Thr

**Comment by pamelaxu213** [comment]
Regarding the latest push on 12-16-2021: 
- There are actually a number of cases where the variant covers more than 1 refseq canonical transcripts. It's good that we fix this. 

- I added small functions here and there so the code might not be straight forward. There might be neater ways to write them but for now I think it's working fine. One of the functions "iterFlatten" was obtained from stackOverflow. Hope it's fine to use it in our script.

**Review by Madelinehazel — APPROVED** [review]
This looks great, time to merge!

**Pull request merged**
